### ISSUE TITLE
Error 404 in links in README

### ISSUE THREAD

**Issue by IgorRozani** [PowerShell/powerShell-Docs.pt-br#2]
In the section [Contribuindo](https://github.com/PowerShell/powerShell-Docs.pt-br#contribuindo), in the README.md has two links that are not working, they are linking two files that doesn't exist in the project.

![image](https://user-images.githubusercontent.com/802968/47239407-9b246980-d3bb-11e8-8f02-9ca5547f9668.png)

The first link is "guia de contribuições", that refers to a CONTRIBUTING.md that doesn't exist.
The second is "guia de estilo", that refers to a STYLE.md that doesn't exist.

**Comment by CeciAc** [comment]
Hello, @IgorRozani

Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [PowerShell/PowerShell-Docs #3149](https://github.com/PowerShell/PowerShell-Docs/issues/3149) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @IgorRozani,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/PowerShell/PowerShell-Docs/issues/3149.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
